apiVersion: v1
kind: Service
metadata:
  name: mario-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mario
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080


