# mario-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # The original template was likely referencing the missing helper.
  # Correct it by using a direct value from values.yaml or a hardcoded name.
  name: {{ .Values.nameOverride | default "mario-app" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mario
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
