# mario-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  # The problematic include "mario-app.fullname" has been removed.
  # Now, use a direct value from values.yaml.
  name: {{ .Values.nameOverride | default "mario-service" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mario
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}

